---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: loadbalancer-pod
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: loadbalancer-pod
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
...